### ISSUE TITLE
doesnt work on gingerbread

### ISSUE THREAD

**Issue by hoholee12** [DeicPro/SH-OTA#1]
am start android.intent.actions.VIEW com.android.browser /data/local/tmp/openssl https://github.com/DeicPro/curl/releases/download/curl/openssl
<tmp/openssl https://github.com/DeicPro/curl/releases/download/curl/openssl
Starting: Intent { act=android.intent.action.VIEW dat=xxxxx }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=xxxxx flg=0x10000000 }

any ideas?

**Comment by DiamondBond** [comment]
android.intent.action.VIEW dat=xxxxx flg=0x10000000
the reference com.android.browser might be to up to date lol
gingerbread will need an older reference, we should take a look at zeppelinrox's v6 supercharger, he had a different method of grabbing files from the internetz, :)

edit
are you still using gingerbread? :'D might be time for an update, im sure your device will have some ics or jb builds available at least, maybe even kitkat.

**Comment by hoholee12** [comment]
the only android device i have right now is a 'korean' galaxy s which is lesser known than international version, and has a almost non-existant community. so im stuck at gingerbread for now.:S

**Comment by DiamondBond** [comment]
oh ok... :) im looking into zepps v6 now to try and find out about launching webpages the way he did.

**Comment by hoholee12** [comment]
this one works:

am start -a android.intent.action.VIEW -n com.android.browser/.BrowserActivity -d https://raw.githubusercontent.com/hoholee12/avcore/master/sched_tuner.sh

you just need to add /.BrowserActivity on the back

but then i still dont know how to make the browser to download the file.....

**Comment by DiamondBond** [comment]
tried the above command on my device (5.1.1_r4) and it opens the file, but you have to long press > save as , im using aosp browser (not chrome) , so it works to an extent, ill try add this with a check for os version (later, im kinda busy now lol) (if gingerbread then use legacy method, if 4.0+ use normal method)

**Comment by DeicPro** [comment]
@hoholee12 yes in gb look you need set the activity to launch an app.. and your script isn't downloaded because this url is for read the code, isnt a file to be download. need upload your script to Releases section on Github

@diamondbond isn't need a method to every version, the method with activity set works to gb to kk (lollipop unknow)

edit:
@hoholee12 else

am start android.intent.actions.VIEW com.android.browser /data/local/tmp/openssl <---- Wtf?https://github.com/DeicPro/curl/releases/download/curl/openssl

try removing download location, can be that the only problem, if not, with activity of browser like you said

**Comment by DeicPro** [comment]
@diamondbond isn't need a method to every version, the method with activity set works to gb to kk (lollipop unknow)

**Comment by DeicPro** [comment]
@hoholee12 else

am start android.intent.actions.VIEW com.android.browser /data/local/tmp/openssl <---- Wtf?https://github.com/DeicPro/curl/releases/download/curl/openssl

I don't think that allowed

**Comment by DeicPro** [comment]
@hoholee12 
create a release with the tag "latest" for example and upload your script, main.sh, curl.sh & ota.sh configured correctly there. when releases a new version of your script change ver="" with the version you put in your script (have to be a string unique, like x.x_latest for example) in ota.sh and edit "latest" release, delete your script & ota.sh press ok, edit latest again, upload your script & ota.sh and done.

**Comment by DeicPro** [comment]
@hoholee12 i fail... always has that have the activity and -a & -n... i confused to myself xD....
im hardcore fixing the script now
