### ISSUE TITLE
Guys you are b8es xD

### ISSUE THREAD

**Issue by DeicPro** [DeicPro/SH-OTA#3]
@DiamondBond @hoholee12 Really need help men, i don't get why break or exit not work sometimes in while...

Seriously, revise the code plis :) 1.2 is near to done & so can add to hybrid, because 1.1 not use curl & is ugly xD...

**Comment by hoholee12** [comment]
Uhhh can you describe the prob with more details plz
its not that im not participating, rather the code is polished enough i didnt feel teh need to look at it.xdd

**Comment by DeicPro** [comment]
@hoholee12 fail break in line 46

**Comment by DeicPro** [comment]
SH-OTA.sh soz xD

**Comment by hoholee12** [comment]
2cb54f169ade86675c66df1bb85dfd8ddbd77b9a

**Comment by DeicPro** [comment]
is same... you only change to a personal possition the then & do, the break that I said you not break the while lol @hoholee12 @DiamondBond 
i may replace while to function but I want know why that break is so gay D:

**Comment by DeicPro** [comment]
bc07e71 mother fucker slash
